export const FUND_ACCOUNT_START = 'FUND_ACCOUNT_START'
export const FUND_ACCOUNT__SUCCESS = 'FUND_ACCOUNT__SUCCESS'
export const FUND_ACCOUNT__FAILED = 'FUND_ACCOUNT__FAILED'

export const FETCHED_ORDERS_DELETE = 'FETCHED_ORDERS_DELETE'
export const FETCHED_ORDERS_START = 'FETCHED_ORDERS_START'
export const FETCHED_ORDERS_SUCCESS = 'FETCHED_ORDERS_SUCCESS'
export const FETCHED_ORDERS_FAILED = 'FETCHED_ORDERS_FAILED'
export const DELELTE_ALL_ORDERS = 'DELELTE_ALL_ORDERS'

export const AUTH_GETUSER = 'AUTH_GETUSER'
export const AUTH_REDIRECT = 'AUTH_REDIRECT'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

export const UPDATE_PROFILE_START ='UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS ='UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED ='UPDATE_PROFILE_FAILED'


